version: '3.1'

services:
  users_dbms:
    image: postgres
    container_name: users_dbms
    hostname: users_dbms
    restart: always
    ports:
      - 10001:5432
    env_file: 
      - .env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080