version: '3.1'

services:
  authors_dbms:
    image: postgres
    container_name: authors_dbms
    hostname: authors_dbms
    restart: always
    ports:
      - 10000:5432
    env_file: 
      - .env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data

  adminer_authors_dbms:
    image: adminer
    container_name: adminer
    hostname: adminer
    restart: always
    ports:
      - 8080:8080