version: '3.1'

services:
    authors_dbms:
        image: postgres
        container_name: authors_dbms
        hostname: authors_dbms
        restart: always
        ports:
            - 10000:5432
        env_file:
            - ../../AuthorsHandler.Repository/Database/.env
        volumes:
            - ../../AuthorsHandler.Repository/Database/scripts:/docker-entrypoint-initdb.d
            # - ./data:/var/lib/postgresql/data
    # adminer_authors_dbms:
    #     image: adminer
    #     container_name: adminer
    #     hostname: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    #         
    # zookeeper:
    #     container_name: zookeeper
    #     image: 'bitnami/zookeeper:3.9.0'
    #     ports:
    #         - '2181:2181'
    #     environment:
    #         - ALLOW_ANONYMOUS_LOGIN=yes
    # kafka:
    #     container_name: kafka
    #     image: 'bitnami/kafka:3.1.0'
    #     ports:
    #         - '9092:9092'
    #     environment:
    #         - KAFKA_BROKER_ID=1
    #         - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    #         - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    #         - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    #         - ALLOW_PLAINTEXT_LISTENER=yes
    #         - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    #     depends_on:
    #         - zookeeer
